// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package zh_db

type Zh struct {
	ID          string
	Link        string
	Title       string
	Article     string
	ArticleGen  string
	TimeCreated string
}
